In [1]:
import pandas as pd
import numpy as np

In [2]:
insta_cart=pd.read_csv('Insta_cart.csv')
insta_cart

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle,department,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,COUNTER,add_to_cart_order_ratio,reorder_ratio
0,2702243,19488,2,1,Select-A-Size White Paper Towels,54,17,paper goods,household,6038,prior,6,1,16,21.0,1,7.159891,0.000302
1,207965,5819,7,1,Baby Carrots,123,4,packaged vegetables fruits,produce,12537,prior,16,5,14,5.0,1,9.526614,0.004556
2,1433879,10895,10,1,Mexican Finely Shredded Cheese,21,16,packaged cheese,dairy eggs,118309,prior,10,1,23,28.0,1,9.955142,0.004508
3,1428542,47209,2,1,Organic Hass Avocado,24,4,fresh fruits,produce,854,prior,47,5,12,3.0,1,6.775011,0.000000
4,2666213,11169,5,0,Raw Local Wildflower Honey,29,13,honeys syrups nectars,pantry,15806,prior,11,6,9,16.0,1,9.218182,2.391509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16217239,2506274,1215,9,1,Kidz All Natural Baked Chicken Nuggets,129,1,frozen appetizers sides,frozen,101433,prior,31,5,13,5.0,1,10.130833,0.272113
16217240,2936033,33819,3,0,Original French Vanilla Yogurt,120,16,yogurt,dairy eggs,17879,prior,3,0,12,30.0,1,8.767628,0.027349
16217241,2828946,38260,1,0,Artisan Pizza Crust with Whole Grain,105,13,doughs gelatins bake mixes,pantry,72897,prior,6,3,12,16.0,1,10.184211,0.028571
16217242,1921413,14992,4,0,Green Beans,83,4,fresh vegetables,produce,33907,prior,30,3,17,1.0,1,9.240669,0.000482
16217243,1272060,29077,18,0,Organic Milk Chocolate Peanut Butter Cups,45,19,candy chocolate,snacks,199492,prior,15,4,15,2.0,1,8.896784,0.021864

In [3]:
insta_cart.columns

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered',
       'product_name', 'aisle_id', 'department_id', 'aisle', 'department',
       'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day',
       'days_since_prior_order', 'COUNTER', 'add_to_cart_order_ratio',
       'reorder_ratio'],
      dtype='object')

In [4]:
insta_cart.user_id.nunique()

206103

In [5]:
user_list=insta_cart.user_id.unique()

In [6]:
random_users=np.random.choice(user_list,size=1000,replace=False)

In [7]:
sample_df=insta_cart[insta_cart['user_id'].isin(random_users)]
sample_df

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle,department,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,COUNTER,add_to_cart_order_ratio,reorder_ratio
110,238733,5334,32,0,Blue Eucalyptus & Lavender Natural Laundry Det...,75,17,laundry,household,69880,prior,40,0,9,14.0,1,10.575103,0.026087
300,153181,7371,26,0,Chocolate Chip Cookie Dough Bar,3,19,energy granola bars,snacks,101508,prior,2,1,11,4.0,1,10.012813,0.132054
328,1308245,25919,2,1,Parmesan Shredded Cheese,21,16,packaged cheese,dairy eggs,33735,prior,5,3,19,30.0,1,9.927955,0.008342
412,1922881,8424,1,1,Broccoli Crown,83,4,fresh vegetables,produce,12205,prior,46,4,11,1.0,1,8.526663,0.022015
1195,369266,5616,24,1,Mexican Papaya,24,4,fresh fruits,produce,140480,prior,23,3,9,8.0,1,8.351562,0.059190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16216385,514064,738,5,1,Almond Breeze Unsweetened Almond Coconut Milk ...,91,16,soy lactosefree,dairy eggs,134477,prior,6,3,7,4.0,1,6.075501,0.151420
16216777,3371739,31338,7,0,Classic Almond Butter,88,13,spreads,pantry,132632,prior,5,0,16,9.0,1,9.512519,0.000312
16216853,1629859,24852,4,1,Banana,24,4,fresh fruits,produce,110938,prior,34,1,23,7.0,1,4.894129,0.000064
16216910,2655054,18288,15,1,Sea Salt Potato Chips,107,19,chips pretzels,snacks,103495,prior,7,4,11,11.0,1,9.252484,0.000308
16217220,2544823,26575,22,1,Cooked Classic Italian Sausage,106,12,hot dogs bacon sausage,meat seafood,110938,prior,6,3,22,8.0,1,11.051913,0.016393

In [8]:
sample_df['user_id'].nunique()

1000

In [9]:
sample_df.reset_index(inplace=True,drop=True)
sample_df

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle,department,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,COUNTER,add_to_cart_order_ratio,reorder_ratio
0,238733,5334,32,0,Blue Eucalyptus & Lavender Natural Laundry Det...,75,17,laundry,household,69880,prior,40,0,9,14.0,1,10.575103,0.026087
1,153181,7371,26,0,Chocolate Chip Cookie Dough Bar,3,19,energy granola bars,snacks,101508,prior,2,1,11,4.0,1,10.012813,0.132054
2,1308245,25919,2,1,Parmesan Shredded Cheese,21,16,packaged cheese,dairy eggs,33735,prior,5,3,19,30.0,1,9.927955,0.008342
3,1922881,8424,1,1,Broccoli Crown,83,4,fresh vegetables,produce,12205,prior,46,4,11,1.0,1,8.526663,0.022015
4,369266,5616,24,1,Mexican Papaya,24,4,fresh fruits,produce,140480,prior,23,3,9,8.0,1,8.351562,0.059190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79433,514064,738,5,1,Almond Breeze Unsweetened Almond Coconut Milk ...,91,16,soy lactosefree,dairy eggs,134477,prior,6,3,7,4.0,1,6.075501,0.151420
79434,3371739,31338,7,0,Classic Almond Butter,88,13,spreads,pantry,132632,prior,5,0,16,9.0,1,9.512519,0.000312
79435,1629859,24852,4,1,Banana,24,4,fresh fruits,produce,110938,prior,34,1,23,7.0,1,4.894129,0.000064
79436,2655054,18288,15,1,Sea Salt Potato Chips,107,19,chips pretzels,snacks,103495,prior,7,4,11,11.0,1,9.252484,0.000308
79437,2544823,26575,22,1,Cooked Classic Italian Sausage,106,12,hot dogs bacon sausage,meat seafood,110938,prior,6,3,22,8.0,1,11.051913,0.016393

In [10]:
sample_df.columns

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered',
       'product_name', 'aisle_id', 'department_id', 'aisle', 'department',
       'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day',
       'days_since_prior_order', 'COUNTER', 'add_to_cart_order_ratio',
       'reorder_ratio'],
      dtype='object')

In [11]:
#reorderd= If the customer has ordered that item or not previously
#add to cart order - order of product in that particular order

In [12]:
#Singular value decomposition

In [13]:
sample_df['product_dup']=sample_df['product_id']
sample_df['user_id_dup']=sample_df['user_id']

<ipython-input-13-d8951fe81471>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_df['product_dup']=sample_df['product_id']
<ipython-input-13-d8951fe81471>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_df['user_id_dup']=sample_df['user_id']

In [14]:
grouped=sample_df.groupby(by=['user_id','product_id'],as_index=False).agg({'product_dup':'count','reordered':'sum',
                                                                          'add_to_cart_order':'mean'})
grouped

       user_id  product_id  product_dup  reordered  add_to_cart_order
0           22        4421            1          0                1.0
1           22        5212            1          0                4.0
2           22        7088            1          0               10.0
3           22       13176            1          1                1.0
4           22       14678            1          0                8.0
...        ...         ...          ...        ...                ...
42063   206194       43961            2          1               14.0
42064   206194       44229            1          1               16.0
42065   206194       44683            1          0                2.0
42066   206194       45104            2          1                7.5
42067   206194       49683            1          0               10.0

[42068 rows x 5 columns]

In [15]:
grouped['reorder_ratio']=grouped['reordered']/grouped['product_dup']
grouped['add_to_cart_order_ratio']=1/grouped['add_to_cart_order']

In [16]:
grouped['ratings']=np.round((grouped['product_dup']+ grouped['reorder_ratio'])* (grouped['add_to_cart_order_ratio']),5)
grouped['ratings']

0        1.00000
1        0.25000
2        0.10000
3        2.00000
4        0.12500
          ...
42063    0.17857
42064    0.12500
42065    0.50000
42066    0.33333
42067    0.10000
Name: ratings, Length: 42068, dtype: float64

In [17]:
recommendations_df=grouped[['user_id','product_id','ratings']]
recommendations_df

       user_id  product_id  ratings
0           22        4421  1.00000
1           22        5212  0.25000
2           22        7088  0.10000
3           22       13176  2.00000
4           22       14678  0.12500
...        ...         ...      ...
42063   206194       43961  0.17857
42064   206194       44229  0.12500
42065   206194       44683  0.50000
42066   206194       45104  0.33333
42067   206194       49683  0.10000

[42068 rows x 3 columns]

In [18]:
recommendations_df['ratings'].max()

33.9697

In [19]:
from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import StandardScaler

scaler = MinMaxScaler((0,5))
scaler.fit(recommendations_df['ratings'].to_numpy().reshape(-1,1))

recommendations_df['ratings']=scaler.transform(recommendations_df['ratings'].to_numpy().reshape(-1,1))
recommendations_df['ratings']

<ipython-input-19-f671bee5d520>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recommendations_df['ratings']=scaler.transform(recommendations_df['ratings'].to_numpy().reshape(-1,1))

0        0.145259
1        0.034823
2        0.012736
3        0.292508
4        0.016417
           ...
42063    0.024305
42064    0.016417
42065    0.071635
42066    0.047093
42067    0.012736
Name: ratings, Length: 42068, dtype: float64

In [20]:
matrix=recommendations_df.pivot_table(values='ratings',columns='user_id',index='product_id')

In [21]:
matrix

user_id,22,249,394,928,1028,1146,1529,1689,1754,2565,...,203647,204202,204216,204310,204399,204533,205446,205928,206187,206194
product_id,,,,,,,,,,,,,,,,,,,,,
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.022553,0.012736

In [22]:
sparse_matrix=matrix.fillna(0)
sparse_matrix

user_id,22,249,394,928,1028,1146,1529,1689,1754,2565,...,203647,204202,204216,204310,204399,204533,205446,205928,206187,206194
product_id,,,,,,,,,,,,,,,,,,,,,
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
49668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
49678,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
49680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
49683,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.022553,0.012736

In [23]:
scores=sparse_matrix.values
U, S, V = np.linalg.svd(scores)

In [24]:
def top_cosine_similarity(data, movie_id, top_n=10):
    index = movie_id # Movie id starts from 1 in the dataset
    movie_row = data[index, :]
    magnitude = np.sqrt(np.einsum('ij, ij -> i', data, data))
    similarity = np.dot(movie_row, data.T) / (magnitude[index] * magnitude)
    sort_indexes = np.argsort(-similarity)
    return sort_indexes[1:top_n+1]

In [25]:
def similiar_movies(matrix,data,indexes,product_id):
    lst=[sparse_matrix.index[i] for i in indexes]
    unique_lst=data[data['product_id'].isin(lst)]['product_name'].unique()[1:]
    print(unique_lst)

In [26]:
k = 30
product_id=sparse_matrix.index[50]
print(sample_df[sample_df['product_id']==product_id]['product_name'].unique())
top_n = 10
sliced = V.T[:,:k] # representative data
indexes = top_cosine_similarity(sliced,50,top_n)
similiar_movies(sparse_matrix,sample_df, indexes,product_id)

['Soda']
['Extra Soft Double Roll Bathroom Tissue' 'Cayenne Pepper'
 'The Original Cream Bars Orange Raspberry Frozen Bars'
 'Delights Chicken Sausage, Egg Whites, & Cheese English Muffin'
 'Spinach And Artichoke Hummus'
 'Organic Turkey, Brown Rice & Chicken Adult Wet Cat Food'
 'Organic Sweet Basil And Roasted Garlic Smoked Sausage'
 'Old Fashioned Hot Dog Buns' 'Pancake Batter, Original']

In [27]:
!pip install surprise

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: surprise in /N/home/u020/dj78/Carbonate/.local/lib/python3.9/site-packages (0.1)
Requirement already satisfied: scikit-surprise in /N/home/u020/dj78/Carbonate/.local/lib/python3.9/site-packages (from surprise) (1.1.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.9/site-packages (from scikit-surprise->surprise) (1.15.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.9/site-packages (from scikit-surprise->surprise) (1.7.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.9/site-packages (from scikit-surprise->surprise) (1.1.0)
Requirement already satisfied: numpy>=1.11.2 in /usr/local/lib/python3.9/site-packages (from scikit-surprise->surprise) (1.22.0)
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

In [28]:
# Singular value decomposition ++ 
from surprise import NMF, SVD, SVDpp, KNNBasic, KNNWithMeans, KNNWithZScore, CoClustering
from surprise.model_selection import cross_validate
from surprise import Reader, Dataset
import time

In [29]:
# A reader is still needed but only the rating_scale param is requiered.
reader = Reader()
data = Dataset.load_from_df(recommendations_df, reader)

In [30]:
user_ids=[x for x in sample_df['user_id'].unique()[:100]]

In [31]:
start=time.time()
final_df=pd.DataFrame()
unique_ids = recommendations_df['product_id'].unique()
for i in user_ids:
    

    # get the list of the ids that the userid 1001 has rated
    iids1001 = recommendations_df.loc[recommendations_df['user_id']==i, 'product_id']

    # remove the rated movies for the recommendations
    products_to_predict = np.setdiff1d(unique_ids,iids1001)


    algo = NMF()
    algo.fit(data.build_full_trainset())

    my_recs = []
    for iid in products_to_predict:
        my_recs.append((iid, algo.predict(uid=i,iid=iid).est,i))

    preds_df=pd.DataFrame(my_recs, columns=['iid', 'predictions','user_id']).sort_values('predictions', ascending=False)
    preds_df=preds_df.drop_duplicates()
    final_df=pd.concat([final_df,preds_df[:10]],axis=0)
end=time.time()
print(end-start)

309.69522523880005

In [32]:
final_df

        iid  predictions  user_id
0         4          1.0    69880
7693  33044          1.0    69880
7673  32961          1.0    69880
7674  32962          1.0    69880
7675  32965          1.0    69880
...     ...          ...      ...
7744  32989          1.0    42492
7745  33000          1.0    42492
7746  33012          1.0    42492
7747  33015          1.0    42492
7748  33020          1.0    42492

[1000 rows x 3 columns]

## Products bought by the user 145935

In [33]:
### showing recommendations for 1 user

In [39]:
product=sample_df[sample_df['user_id']==69880]['product_name'].unique().tolist()
product

['Blue Eucalyptus & Lavender Natural Laundry Detergent',
 'Roasted Salted Cashews',
 'Organic Jasmine Rice',
 'Organic Lite Coconut Milk',
 'Orange Bell Pepper',
 'Organic Strawberries',
 'Organic Black Beans',
 'Organic Half & Half',
 'Raspberries',
 'Kids Organic Chocolate Chip ZBars',
 'Organic Baby Spinach',
 'Broccoli Crown',
 'Organic Avocado',
 'YoKids Squeezers Organic Low-Fat Yogurt, Strawberry',
 'Gluten Free Lemonzest Nutrition bar',
 'Organic Zucchini',
 'Organic Skim Milk',
 'Mild Salsa',
 'Frozen Organic Wild Blueberries',
 'Organic Baby Arugula',
 'Whipped Cream Cheese',
 'Chocolate Dipped Coconut',
 '100% Juice Medley Of Fruits',
 'Organic Sweetened Cranberries',
 'Original Hummus',
 'Lowfat Vanilla Yogurt',
 'Organic Bartlett Pear',
 'Red Raspberries',
 'Organic Fuji Apple',
 'Organic Garlic',
 'Unsalted Butter',
 'Organic Fat Free Refried Pinto Beans',
 'Shredded Mild Cheddar Cheese',
 'Tangerine 1,000 mg Vitamin C Dietary Supplement',
 'Organic American Cheese Singles',
 'Organic Banana',
 'Potato Chips, Lightly Salted',
 'Shredded Mozzarella',
 'Limes',
 'Organic Blueberries',
 'Creamy Deluxe Shells & Real Aged Cheddar Sauce',
 'Organic Brown Rice',
 'Chocolate Peppermint Stick Bar',
 'Organic Yellow Onion',
 'Large Lemon',
 'Cantaloupe',
 'Crunchy Pumpkin Spice Flax Granola Bars',
 'Organic Peeled Whole Baby Carrots',
 'Original Tortilla Strips',
 'Natural Crackers',
 'Organic Three Grain Tempeh',
 '100% Mango Juice',
 'Saltine Crackers',
 'Organic Mild Salsa',
 'Burrata alla Panna',
 'Organic Baby Carrots',
 'Organic Frozen Peas',
 'Shredded Parmesan',
 'Organic Bosc Pear',
 "S'mores Luna Bar",
 'Organic Italian Parsley Bunch',
 'Organic Baby Rainbow Carrots',
 'Panda Puffs Peanut Butter Cereal',
 'Ground Coriander',
 'Four Cheese Pasta Sauce',
 'Organic Extra Firm Tofu',
 'Active Dry Yeast',
 'Organic Frozen Mango Chunks',
 'Strawberries',
 'Seven Grain Crispy Tenders',
 'Sharp Cheddar Cheese',
 'Veggie Pepperoni Pizza',
 'Cinnamon Raisin Bread',
 'Light Frosted Amazon Flakes',
 'Bag of Organic Bananas',
 'Salted Butter',
 'Organic Capellini',
 'Sour Cream',
 'Goat Cheese Crumbles',
 'Organic Baby Bella Mushrooms',
 'Cheddar Snack Crackers Cheddar Bunnies',
 'Madras Lentils Indian Cuisine',
 'Carrots',
 'Whole Wheat Pita Bread',
 'Rainbow Bell Peppers',
 'Aged White Cheddar Baked Rice & Corn Puffs Gluten Free Lunch Packs',
 'Organic Cilantro',
 'Organic Sliced Peaches',
 'Thin Whole Wheat Sandwich Buns',
 'Organic Tamari Gluten-Free Soy Sauce',
 'Organic Cinnamon Sticks',
 'Peanut Butter Creamy With Salt',
 'Matar-Paneer',
 'Whole Wheat English Muffins',
 'Marinara Sauce',
 'Edamame In Pod',
 'Mushroom Baby Bella',
 "Organic D'Anjou Pears",
 'Organic Whole Strawberries',
 'Jumbo Veggie Protein Smart Dogs Links',
 'Grape White/Green Seedless',
 'Organic Pumpkin',
 'Organic Bunny Fruit Snacks Berry Patch',
 'Tommy/Kent/Keitt/Haden Mango',
 'Steel Cut Oats',
 'Original Tofurky Deli Slices',
 'Organic Carrots & Ranch Dip',
 'Organic Thai Coconut Curry Hummus',
 'Pizza Sauce',
 'Organic Broccoli',
 'Creamy Almond Butter',
 'Cauliettes Culinary Cuts',
 'Brightening Facial Scrub Sea Kelp + CGF',
 'Premium Pure Cane Granulated Sugar',
 'Organic Garbanzo Beans',
 'Guacamole',
 'Whole Care Spearmint Toothpaste',
 'Organic Dijon Mustard',
 'Stir Fry Pad Thai',
 'Organic Sea Salt Roasted Seaweed Snacks',
 'Organic Brown Rice Crisps Cereal']

## Recommendations for 1 user

In [40]:
final_df1=final_df[final_df['user_id']==69880]
product_recommendations=sample_df[sample_df['product_id'].isin(final_df1['iid'])]['product_name'].unique().tolist()
product_recommendations

['Original Recipe Rice Pudding',
 'Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce',
 "Blazin' Beef Recipe Dog Food",
 'Sliced Peaches',
 "Mini I.D.'s French Vanilla Creamer, Singles",
 'ReNu Sensitive Gentle Formula Multi-Purpose Solution',
 'Invisible Solid Unscented Deodorant',
 'Yellow Corn Extra Thin Tortillas',
 'Cake, Lemon',
 'Natural Shredded Monterey Jack Cheese']

In [36]:
#SVD ++
import time
from tqdm import tqdm
start=time.time()
svdpp_df=pd.DataFrame()
for i in tqdm(user_ids1):
    iids1001 = recommendations_df.loc[recommendations_df['user_id']==i, 'product_id']

    # remove the rated movies for the recommendations
    products_to_predict = np.setdiff1d(unique_ids,iids1001)
    
    algo = SVDpp()
    algo.fit(data.build_full_trainset())
    

    my_recs = []
    for iid in products_to_predict:
        my_recs.append((iid, algo.predict(uid=i,iid=iid).est))

    svd_predictions=pd.DataFrame(my_recs, columns=['iid', 'predictions']).sort_values('predictions', ascending=False)
    svd_predictions.drop_duplicates(inplace=True)
    svdpp_df=pd.concat([svdpp_df,svd_predictions[:10]],axis=0)
end=time.time()
print(end-start)

NameError: name 'user_ids1' is not defined

In [ ]:
svdpp_df

In [ ]:
product_recommendations=sample_df[sample_df['product_id'].isin(svd_predictions['iid'])]['product_name'].unique().tolist()

In [ ]:
product_recommendations

In [ ]:
user_ids1=user_ids[:2]

In [42]:
#user based svd recommendations
from tqdm import tqdm
svd_df=pd.DataFrame()

start=time.time()
for i in tqdm(user_ids):
    iids1001 = recommendations_df.loc[recommendations_df['user_id']==i, 'product_id']

    # remove the rated movies for the recommendations
    products_to_predict = np.setdiff1d(unique_ids,iids1001)
    
    algo = SVD()
    algo.fit(data.build_full_trainset())
    my_recs = []
    for iid in products_to_predict:
        my_recs.append((iid, algo.predict(uid=i,iid=iid).est))

    svd=pd.DataFrame(my_recs, columns=['iid', 'predictions']).sort_values('predictions', ascending=False)
    svd.drop_duplicates(inplace=True)
    svd['user_id']=i
    svd_df=pd.concat([svd_df,svd[:10]],axis=0)
end=time.time()
print(end-start)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100/100 [04:41<00:00,  2.81s/it]

281.360604763031

In [43]:
svd_df

        iid  predictions  user_id
0         4            1    69880
7693  33044            1    69880
7673  32961            1    69880
7674  32962            1    69880
7675  32965            1    69880
...     ...          ...      ...
7744  32989            1    42492
7745  33000            1    42492
7746  33012            1    42492
7747  33015            1    42492
7748  33020            1    42492

[1000 rows x 3 columns]

In [49]:
#products bought by the user 145935
product=sample_df[sample_df['user_id']==69880]['product_name'].unique().tolist()
product

['Blue Eucalyptus & Lavender Natural Laundry Detergent',
 'Roasted Salted Cashews',
 'Organic Jasmine Rice',
 'Organic Lite Coconut Milk',
 'Orange Bell Pepper',
 'Organic Strawberries',
 'Organic Black Beans',
 'Organic Half & Half',
 'Raspberries',
 'Kids Organic Chocolate Chip ZBars',
 'Organic Baby Spinach',
 'Broccoli Crown',
 'Organic Avocado',
 'YoKids Squeezers Organic Low-Fat Yogurt, Strawberry',
 'Gluten Free Lemonzest Nutrition bar',
 'Organic Zucchini',
 'Organic Skim Milk',
 'Mild Salsa',
 'Frozen Organic Wild Blueberries',
 'Organic Baby Arugula',
 'Whipped Cream Cheese',
 'Chocolate Dipped Coconut',
 '100% Juice Medley Of Fruits',
 'Organic Sweetened Cranberries',
 'Original Hummus',
 'Lowfat Vanilla Yogurt',
 'Organic Bartlett Pear',
 'Red Raspberries',
 'Organic Fuji Apple',
 'Organic Garlic',
 'Unsalted Butter',
 'Organic Fat Free Refried Pinto Beans',
 'Shredded Mild Cheddar Cheese',
 'Tangerine 1,000 mg Vitamin C Dietary Supplement',
 'Organic American Cheese Singles',
 'Organic Banana',
 'Potato Chips, Lightly Salted',
 'Shredded Mozzarella',
 'Limes',
 'Organic Blueberries',
 'Creamy Deluxe Shells & Real Aged Cheddar Sauce',
 'Organic Brown Rice',
 'Chocolate Peppermint Stick Bar',
 'Organic Yellow Onion',
 'Large Lemon',
 'Cantaloupe',
 'Crunchy Pumpkin Spice Flax Granola Bars',
 'Organic Peeled Whole Baby Carrots',
 'Original Tortilla Strips',
 'Natural Crackers',
 'Organic Three Grain Tempeh',
 '100% Mango Juice',
 'Saltine Crackers',
 'Organic Mild Salsa',
 'Burrata alla Panna',
 'Organic Baby Carrots',
 'Organic Frozen Peas',
 'Shredded Parmesan',
 'Organic Bosc Pear',
 "S'mores Luna Bar",
 'Organic Italian Parsley Bunch',
 'Organic Baby Rainbow Carrots',
 'Panda Puffs Peanut Butter Cereal',
 'Ground Coriander',
 'Four Cheese Pasta Sauce',
 'Organic Extra Firm Tofu',
 'Active Dry Yeast',
 'Organic Frozen Mango Chunks',
 'Strawberries',
 'Seven Grain Crispy Tenders',
 'Sharp Cheddar Cheese',
 'Veggie Pepperoni Pizza',
 'Cinnamon Raisin Bread',
 'Light Frosted Amazon Flakes',
 'Bag of Organic Bananas',
 'Salted Butter',
 'Organic Capellini',
 'Sour Cream',
 'Goat Cheese Crumbles',
 'Organic Baby Bella Mushrooms',
 'Cheddar Snack Crackers Cheddar Bunnies',
 'Madras Lentils Indian Cuisine',
 'Carrots',
 'Whole Wheat Pita Bread',
 'Rainbow Bell Peppers',
 'Aged White Cheddar Baked Rice & Corn Puffs Gluten Free Lunch Packs',
 'Organic Cilantro',
 'Organic Sliced Peaches',
 'Thin Whole Wheat Sandwich Buns',
 'Organic Tamari Gluten-Free Soy Sauce',
 'Organic Cinnamon Sticks',
 'Peanut Butter Creamy With Salt',
 'Matar-Paneer',
 'Whole Wheat English Muffins',
 'Marinara Sauce',
 'Edamame In Pod',
 'Mushroom Baby Bella',
 "Organic D'Anjou Pears",
 'Organic Whole Strawberries',
 'Jumbo Veggie Protein Smart Dogs Links',
 'Grape White/Green Seedless',
 'Organic Pumpkin',
 'Organic Bunny Fruit Snacks Berry Patch',
 'Tommy/Kent/Keitt/Haden Mango',
 'Steel Cut Oats',
 'Original Tofurky Deli Slices',
 'Organic Carrots & Ranch Dip',
 'Organic Thai Coconut Curry Hummus',
 'Pizza Sauce',
 'Organic Broccoli',
 'Creamy Almond Butter',
 'Cauliettes Culinary Cuts',
 'Brightening Facial Scrub Sea Kelp + CGF',
 'Premium Pure Cane Granulated Sugar',
 'Organic Garbanzo Beans',
 'Guacamole',
 'Whole Care Spearmint Toothpaste',
 'Organic Dijon Mustard',
 'Stir Fry Pad Thai',
 'Organic Sea Salt Roasted Seaweed Snacks',
 'Organic Brown Rice Crisps Cereal']

In [50]:
#sample recommendations for 1 user
svd_df1=svd_df[svd_df['user_id']==69880]
product_recommendations=sample_df[sample_df['product_id'].isin(svd_df1['iid'])]['product_name'].unique().tolist()
product_recommendations

['Original Recipe Rice Pudding',
 'Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce',
 "Blazin' Beef Recipe Dog Food",
 'Sliced Peaches',
 "Mini I.D.'s French Vanilla Creamer, Singles",
 'ReNu Sensitive Gentle Formula Multi-Purpose Solution',
 'Invisible Solid Unscented Deodorant',
 'Yellow Corn Extra Thin Tortillas',
 'Cake, Lemon',
 'Natural Shredded Monterey Jack Cheese']

In [47]:
clustering_df=pd.DataFrame()

start=time.time()

for i in tqdm(user_ids):
    iids1001 = recommendations_df.loc[recommendations_df['user_id']==i, 'product_id']

    # remove the rated movies for the recommendations
    products_to_predict = np.setdiff1d(unique_ids,iids1001)
    algo = CoClustering()
    algo.fit(data.build_full_trainset())
    
    my_recs = []
    for iid in products_to_predict:
        my_recs.append((iid, algo.predict(uid=i,iid=iid).est))

    co_clustering=pd.DataFrame(my_recs, columns=['iid', 'predictions']).sort_values('predictions', ascending=False)
    co_clustering['user_id']=i
    co_clustering=co_clustering.drop_duplicates()
    clustering_df=pd.concat([clustering_df,co_clustering[:10]],axis=0)
end=time.time()
print(end-start)

  0%|          | 0/100 [00:00<?, ?it/s]<ipython-input-47-b14b4a24032e>:11: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  algo.fit(data.build_full_trainset())
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100/100 [04:21<00:00,  2.62s/it]

261.9322991371155

In [48]:
clustering_df

        iid  predictions  user_id
2782  11885     1.981187    69880
0         4     1.000000    69880
7682  33000     1.000000    69880
7673  32961     1.000000    69880
7674  32962     1.000000    69880
...     ...          ...      ...
8851  37710     1.254718    42492
8490  36127     1.230909    42492
3329  14084     1.199163    42492
1174   5031     1.199163    42492
7054  30169     1.188052    42492

[1000 rows x 3 columns]

In [51]:
#products bought by the user 145935
product=sample_df[sample_df['user_id']==69880]['product_name'].unique().tolist()
product

['Blue Eucalyptus & Lavender Natural Laundry Detergent',
 'Roasted Salted Cashews',
 'Organic Jasmine Rice',
 'Organic Lite Coconut Milk',
 'Orange Bell Pepper',
 'Organic Strawberries',
 'Organic Black Beans',
 'Organic Half & Half',
 'Raspberries',
 'Kids Organic Chocolate Chip ZBars',
 'Organic Baby Spinach',
 'Broccoli Crown',
 'Organic Avocado',
 'YoKids Squeezers Organic Low-Fat Yogurt, Strawberry',
 'Gluten Free Lemonzest Nutrition bar',
 'Organic Zucchini',
 'Organic Skim Milk',
 'Mild Salsa',
 'Frozen Organic Wild Blueberries',
 'Organic Baby Arugula',
 'Whipped Cream Cheese',
 'Chocolate Dipped Coconut',
 '100% Juice Medley Of Fruits',
 'Organic Sweetened Cranberries',
 'Original Hummus',
 'Lowfat Vanilla Yogurt',
 'Organic Bartlett Pear',
 'Red Raspberries',
 'Organic Fuji Apple',
 'Organic Garlic',
 'Unsalted Butter',
 'Organic Fat Free Refried Pinto Beans',
 'Shredded Mild Cheddar Cheese',
 'Tangerine 1,000 mg Vitamin C Dietary Supplement',
 'Organic American Cheese Singles',
 'Organic Banana',
 'Potato Chips, Lightly Salted',
 'Shredded Mozzarella',
 'Limes',
 'Organic Blueberries',
 'Creamy Deluxe Shells & Real Aged Cheddar Sauce',
 'Organic Brown Rice',
 'Chocolate Peppermint Stick Bar',
 'Organic Yellow Onion',
 'Large Lemon',
 'Cantaloupe',
 'Crunchy Pumpkin Spice Flax Granola Bars',
 'Organic Peeled Whole Baby Carrots',
 'Original Tortilla Strips',
 'Natural Crackers',
 'Organic Three Grain Tempeh',
 '100% Mango Juice',
 'Saltine Crackers',
 'Organic Mild Salsa',
 'Burrata alla Panna',
 'Organic Baby Carrots',
 'Organic Frozen Peas',
 'Shredded Parmesan',
 'Organic Bosc Pear',
 "S'mores Luna Bar",
 'Organic Italian Parsley Bunch',
 'Organic Baby Rainbow Carrots',
 'Panda Puffs Peanut Butter Cereal',
 'Ground Coriander',
 'Four Cheese Pasta Sauce',
 'Organic Extra Firm Tofu',
 'Active Dry Yeast',
 'Organic Frozen Mango Chunks',
 'Strawberries',
 'Seven Grain Crispy Tenders',
 'Sharp Cheddar Cheese',
 'Veggie Pepperoni Pizza',
 'Cinnamon Raisin Bread',
 'Light Frosted Amazon Flakes',
 'Bag of Organic Bananas',
 'Salted Butter',
 'Organic Capellini',
 'Sour Cream',
 'Goat Cheese Crumbles',
 'Organic Baby Bella Mushrooms',
 'Cheddar Snack Crackers Cheddar Bunnies',
 'Madras Lentils Indian Cuisine',
 'Carrots',
 'Whole Wheat Pita Bread',
 'Rainbow Bell Peppers',
 'Aged White Cheddar Baked Rice & Corn Puffs Gluten Free Lunch Packs',
 'Organic Cilantro',
 'Organic Sliced Peaches',
 'Thin Whole Wheat Sandwich Buns',
 'Organic Tamari Gluten-Free Soy Sauce',
 'Organic Cinnamon Sticks',
 'Peanut Butter Creamy With Salt',
 'Matar-Paneer',
 'Whole Wheat English Muffins',
 'Marinara Sauce',
 'Edamame In Pod',
 'Mushroom Baby Bella',
 "Organic D'Anjou Pears",
 'Organic Whole Strawberries',
 'Jumbo Veggie Protein Smart Dogs Links',
 'Grape White/Green Seedless',
 'Organic Pumpkin',
 'Organic Bunny Fruit Snacks Berry Patch',
 'Tommy/Kent/Keitt/Haden Mango',
 'Steel Cut Oats',
 'Original Tofurky Deli Slices',
 'Organic Carrots & Ranch Dip',
 'Organic Thai Coconut Curry Hummus',
 'Pizza Sauce',
 'Organic Broccoli',
 'Creamy Almond Butter',
 'Cauliettes Culinary Cuts',
 'Brightening Facial Scrub Sea Kelp + CGF',
 'Premium Pure Cane Granulated Sugar',
 'Organic Garbanzo Beans',
 'Guacamole',
 'Whole Care Spearmint Toothpaste',
 'Organic Dijon Mustard',
 'Stir Fry Pad Thai',
 'Organic Sea Salt Roasted Seaweed Snacks',
 'Organic Brown Rice Crisps Cereal']

In [52]:
#sample recommendations for 1 user
clustering_df1=clustering_df[clustering_df['user_id']==69880]
product_recommendations=sample_df[sample_df['product_id'].isin(clustering_df1['iid'])]['product_name'].unique().tolist()
product_recommendations

['Pure Irish Butter',
 'Original Recipe Rice Pudding',
 'Sparkling Water, Bottles',
 'Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce',
 "Blazin' Beef Recipe Dog Food",
 'Sliced Peaches',
 "Mini I.D.'s French Vanilla Creamer, Singles",
 'ReNu Sensitive Gentle Formula Multi-Purpose Solution',
 'Invisible Solid Unscented Deodorant',
 'Cake, Lemon']

In [53]:
cv = []
# Iterate over all recommender system algorithms
for recsys in [NMF(), SVD(), CoClustering()]:
    # Perform cross validation
    tmp = cross_validate(recsys, data, measures=['RMSE'], cv=3, verbose=False)
    cv.append((str(recsys).split(' ')[0].split('.')[-1], tmp['test_rmse'].mean()))

results_df=pd.DataFrame(cv, columns=['RecSys', 'RMSE'])

In [54]:
results_df

         RecSys      RMSE
0           NMF  0.938834
1           SVD  0.938688
2  CoClustering  0.938898

In [55]:
#content based filtering based on products
df=sample_df[['product_name','aisle','department']]
df

,product_name,aisle,department
0,Blue Eucalyptus & Lavender Natural Laundry Det...,laundry,household
1,Chocolate Chip Cookie Dough Bar,energy granola bars,snacks
2,Parmesan Shredded Cheese,packaged cheese,dairy eggs
3,Broccoli Crown,fresh vegetables,produce
4,Mexican Papaya,fresh fruits,produce
...,...,...,...
79433,Almond Breeze Unsweetened Almond Coconut Milk ...,soy lactosefree,dairy eggs
79434,Classic Almond Butter,spreads,pantry
79435,Banana,fresh fruits,produce
79436,Sea Salt Potato Chips,chips pretzels,snacks
79437,Cooked Classic Italian Sausage,hot dogs bacon sausage,meat seafood

In [56]:
df.drop_duplicates(inplace=True)

/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [57]:
df['product_info']=df['product_name']+ " " + df['department'] + " " + df['aisle']

<ipython-input-57-929383c11620>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['product_info']=df['product_name']+ " " + df['department'] + " " + df['aisle']

In [58]:
df.reset_index(inplace=True,drop=True)
df['product_info']

0        Blue Eucalyptus & Lavender Natural Laundry Det...
1        Chocolate Chip Cookie Dough Bar snacks energy ...
2        Parmesan Shredded Cheese dairy eggs packaged c...
3                  Broccoli Crown produce fresh vegetables
4                      Mexican Papaya produce fresh fruits
                               ...
11633    Cauliflower, Broccoli & Red Peppers with Brown...
11634    White Regular Paper Towel Rolls household pape...
11635    Beach Defense Water + Sun Barrier Spray Sunscr...
11636       Wastebasket Liners household trash bags liners
11637    Organic Seed Your Soul Strawberry Lemonade Chi...
Name: product_info, Length: 11638, dtype: object

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['product_info'])
vectorizer.get_feature_names_out()
print(X.shape)

(11638, 4538)

In [60]:
from sklearn.metrics.pairwise import linear_kernel
cos_sim=linear_kernel(X,X)

In [61]:
indices = pd.Series(df.index, index=df['product_info'].unique()).drop_duplicates()
indices

Blue Eucalyptus & Lavender Natural Laundry Detergent household laundry                             0
Chocolate Chip Cookie Dough Bar snacks energy granola bars                                         1
Parmesan Shredded Cheese dairy eggs packaged cheese                                                2
Broccoli Crown produce fresh vegetables                                                            3
Mexican Papaya produce fresh fruits                                                                4
                                                                                               ...
Cauliflower, Broccoli & Red Peppers with Brown Rice in a Butter Sauce frozen frozen produce    11633
White Regular Paper Towel Rolls household paper goods                                          11634
Beach Defense Water + Sun Barrier Spray Sunscreen Spf 70 personal care body lotions soap       11635
Wastebasket Liners household trash bags liners                                                 11636
Organic Seed Your Soul Strawberry Lemonade Chia Vitality Beverage beverages refrigerated       11637
Length: 11638, dtype: int64

In [62]:
unique_products=df['product_name'].unique().tolist()
len(unique_products)

11638

In [63]:
def get_recommendations(title, cosine_sim=cos_sim):
    # Get the index of the movie that matches the title
    dept= df[df['product_name']==title]['department']
    
    aisle=df[df['product_name']==title]['aisle']
    title=title + " " + dept.item() + " " + aisle.item()
    idx = indices[title]
    

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))
    

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df['product_name'].iloc[movie_indices]

In [64]:

dataframe=pd.DataFrame()
for i in tqdm(unique_products):
    recommended=pd.DataFrame()
    product_reccomended=get_recommendations(i,cos_sim).tolist()
    recommended['product_name']=i
    recommended['recommended_products']=product_reccomended
    recommended.fillna(i,inplace=True)
    dataframe=pd.concat([dataframe,recommended],axis=0)
    
dataframe

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 11638/11638 [02:26<00:00, 79.34it/s]

,product_name,recommended_products
0,Blue Eucalyptus & Lavender Natural Laundry Det...,Natural Liquid Laundry Detergent - Blue Eucaly...
1,Blue Eucalyptus & Lavender Natural Laundry Det...,Lavender Scent Laundry Detergent
2,Blue Eucalyptus & Lavender Natural Laundry Det...,Fresh Scent Laundry Detergent
3,Blue Eucalyptus & Lavender Natural Laundry Det...,HE Original Liquid Laundry Detergent
4,Blue Eucalyptus & Lavender Natural Laundry Det...,Original Liquid Laundry Detergent
...,...,...
5,Organic Seed Your Soul Strawberry Lemonade Chi...,Organic Strawberry Lemonade
6,Organic Seed Your Soul Strawberry Lemonade Chi...,Organic Vitality Snack Chia Squeeze Strawberry...
7,Organic Seed Your Soul Strawberry Lemonade Chi...,Lemonade with Mango
8,Organic Seed Your Soul Strawberry Lemonade Chi...,Raspberry Lemonade
9,Organic Seed Your Soul Strawberry Lemonade Chi...,With Raspberry Lemonade

In [71]:
lst=['product_1','product_2','product_3','product_4','product_5','product_6','product_7','product_8','product_9','product_10']

In [74]:
lst2=[]
for i in range(0,11638):
    lst2.extend(lst)
len(lst2)

116380

In [75]:
dataframe['product_no']=lst2
dataframe

,product_name,recommended_products,product_no
0,Blue Eucalyptus & Lavender Natural Laundry Det...,Natural Liquid Laundry Detergent - Blue Eucaly...,product_1
1,Blue Eucalyptus & Lavender Natural Laundry Det...,Lavender Scent Laundry Detergent,product_2
2,Blue Eucalyptus & Lavender Natural Laundry Det...,Fresh Scent Laundry Detergent,product_3
3,Blue Eucalyptus & Lavender Natural Laundry Det...,HE Original Liquid Laundry Detergent,product_4
4,Blue Eucalyptus & Lavender Natural Laundry Det...,Original Liquid Laundry Detergent,product_5
...,...,...,...
5,Organic Seed Your Soul Strawberry Lemonade Chi...,Organic Strawberry Lemonade,product_6
6,Organic Seed Your Soul Strawberry Lemonade Chi...,Organic Vitality Snack Chia Squeeze Strawberry...,product_7
7,Organic Seed Your Soul Strawberry Lemonade Chi...,Lemonade with Mango,product_8
8,Organic Seed Your Soul Strawberry Lemonade Chi...,Raspberry Lemonade,product_9
9,Organic Seed Your Soul Strawberry Lemonade Chi...,With Raspberry Lemonade,product_10

In [76]:
prods_rec=dataframe.pivot(values='recommended_products',columns='product_no',index='product_name')
prods_rec

product_no,product_1,product_10,product_2,product_3,product_4,product_5,product_6,product_7,product_8,product_9
product_name,,,,,,,,,,
#2 Coffee Filters,Compostable Coffee Filters,Organic Whole Bean Coffee,Coffee,Compostable Basket Coffee Filters,Natural Brown Basket Style Coffee Filters,Natural Brown Cone Style Coffee Filters #4,Instant Coffee,Black Coffee,Natural Brown Paper #2 Size Cone Coffee Filters,Organic Instant Coffee
0% Fat Free Organic Milk,"Milk, Organic, Fat Free",Organic 2% Milk,Organic Fat-Free Milk,0% Fat Free Organic Milk,Fat Free Milk,Dairy Pure Fat Free Milk,Fat Free Vitamin A & D Milk,Vitamin A & D Fat Free Milk,Organic Whole Milk,Organic Whole Milk
0% Fat Organic Greek Vanilla Yogurt,Vanilla Greek Yogurt 0% Fat,Low Fat Vanilla Yogurt,Fat Free Vanilla Yogurt,Organic Vanilla Bean Greek Yogurt,Greek 0% Fat Strawberry on the Bottom Yogurt,0% Fat Strawberry Greek Yogurt,Honey Vanilla Greek Yogurt,Greek 100 Protein Vanilla Fat Free Yogurt,Non Fat Greek Yogurt,Organic Greek Fat Free Plain Yogurt
0% Fat Strawberry Greek Yogurt,0% Fat Strawberry Greek Yogurt,Greek Strawberry Nonfat Yogurt,Fat Free Strawberry Yogurt,Dairy Free Greek Yogurt Strawberry,Vanilla Greek Yogurt 0% Fat,Low-Fat Strawberry Banana on the Bottom Greek ...,0% Fat Organic Greek Vanilla Yogurt,Non Fat Greek Yogurt,Oikos Fat Free Strawberry Greek Yogurt,Strawberry on the Bottom Nonfat Greek Yogurt
0% Fat Superfruits Greek Yogurt,Vanilla Greek Yogurt 0% Fat,Honey Greek Yogurt,Greek 0% Fat Strawberry on the Bottom Yogurt,0% Fat Strawberry Greek Yogurt,0% Fat Organic Greek Vanilla Yogurt,Non Fat Greek Yogurt,Organic Greek Fat Free Plain Yogurt,Non-Fat Blueberry on the Bottom Greek Yogurt,Low-Fat Mango on the Bottom Greek Yogurt,Plain Non-Fat Greek Yogurt
...,...,...,...,...,...,...,...,...,...,...
gel hand wash sea minerals,Sweet Water Hand Wash,Basil & Lime Liquid Hand Soap,Foaming Hand Wash Sweet Water,Spring Water Body Wash,Citrus & Ginger Body Wash,Bearglove Body Wash,Lemon Scented Hand Soap,Gold Liquid Hand Soap,"Hand Wash, Foaming, Green Tea + Aloe",Deep Moisture Body Wash
of Hanover 100 Calorie Pretzels Mini,Mini Pretzels,Sea Salt Mini Popcorn,Gluten Free Mini Pretzels,Fat Free Unsalted Mini Pretzels,Pretzels Original Thins,Organic Spelt Pretzels,High Protein Pretzels,Butter Snap Pretzels,Gluten Free Big Pretzels,Dark Chocolate Pretzels with Sea Salt
smart Blend Chicken & Rice Formula Dry Dog Food,Chunky Beef with Vegetables & Brown Rice Dog Food,Organix Grain Free Turkey & Vegetable Dog Food,Kickin' Chicken Recipe Dog Food,"Miniature Dog Treats, Chicken Formula",Prepared Meals Roasted Chicken Recipe Wet Dog...,Meaty Ground Dinner With Chopped Chicken Dog Food,Small Dog Biscuits,Grain Free Chicken Carrots & Peas Ground Wet D...,Blazin' Beef Recipe Dog Food,Chunky Beef Meaty Ground Dog Food
smartwaterÂ® Electrolyte Enhanced Water,smartwaterÂ® Electrolyte Enhanced Water,Sparkling Seltzer Water,Electrolyte Enhanced Water,Electrolyte Water,Smartwater,Water,Sparkling Water,"Water, Sparkling",Seltzer Water,Pure Water
with Crispy Almonds Cereal,Cereal,Peanut Butter Cereal,Original Cereal,Organic Gluten Free Crispy Brown Rice Cereal,Rice Cereal,Granola Cereal,Honey Bunches With Almonds Cereal,Cinnamon Cereal,Organic Whole O's Gluten Free Cereal,Go Lean Cereal

In [77]:
best_preds=final_df.drop(columns=['predictions'])
best_preds

        iid  user_id
0         4    69880
7693  33044    69880
7673  32961    69880
7674  32962    69880
7675  32965    69880
...     ...      ...
7744  32989    42492
7745  33000    42492
7746  33012    42492
7747  33015    42492
7748  33020    42492

[1000 rows x 2 columns]

In [78]:
lst=['product_1','product_2','product_3','product_4','product_5','product_6','product_7','product_8','product_9','product_10']

In [79]:
len(lst1)

NameError: name 'lst1' is not defined

In [80]:
lst1=[]
for i in range(100):
    lst1.extend(lst)
lst1

['product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10',
 'product_1',
 'product_2',
 'product_3',
 'product_4',
 'product_5',
 'product_6',
 'product_7',
 'product_8',
 'product_9',
 'product_10']

In [81]:
best_preds['product_no']=lst1
best_preds

        iid  user_id  product_no
0         4    69880   product_1
7693  33044    69880   product_2
7673  32961    69880   product_3
7674  32962    69880   product_4
7675  32965    69880   product_5
...     ...      ...         ...
7744  32989    42492   product_6
7745  33000    42492   product_7
7746  33012    42492   product_8
7747  33015    42492   product_9
7748  33020    42492  product_10

[1000 rows x 3 columns]

In [82]:
best_preds['iid'].value_counts()

4        99
32989    76
33015    73
33012    73
33000    72
33020    68
32982    68
33021    63
32981    60
32980    50
33024    48
32971    42
33027    35
32968    28
32965    26
33031    23
33037    18
32962    14
32961    11
33041    11
32959     6
33043     5
33045     3
33044     3
33086     3
33081     2
32952     2
33065     2
33060     2
33071     2
32955     2
5619      1
14409     1
3025      1
33058     1
33089     1
35958     1
11885     1
33050     1
33080     1
33056     1
Name: iid, dtype: int64

In [83]:
names=sample_df[['product_id','product_name']]
names.rename(columns={'product_id':'iid'},inplace=True)

/usr/local/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [84]:
product_names=pd.merge(best_preds,names,how='inner',on=['iid'])
product_names.drop(columns=['iid'],inplace=True)
product_names

       user_id product_no                                       product_name
0        69880  product_1  Smart Ones Classic Favorites Mini Rigatoni Wit...
1        69880  product_1  Smart Ones Classic Favorites Mini Rigatoni Wit...
2        69880  product_1  Smart Ones Classic Favorites Mini Rigatoni Wit...
3       101508  product_1  Smart Ones Classic Favorites Mini Rigatoni Wit...
4       101508  product_1  Smart Ones Classic Favorites Mini Rigatoni Wit...
...        ...        ...                                                ...
10700    21253  product_4                                       Carrot Chips
10701    21253  product_4                                       Carrot Chips
10702    21253  product_4                                       Carrot Chips
10703    21253  product_4                                       Carrot Chips
10704    21253  product_4                                       Carrot Chips

[10705 rows x 3 columns]

In [85]:
product_names.drop_duplicates(inplace=True)

In [86]:
tableau=product_names.pivot(columns='product_no',index='user_id',values='product_name')
tableau

product_no,product_1,product_10,product_2,product_3,product_4,product_5,product_6,product_7,product_8,product_9
user_id,,,,,,,,,,
394,Smart Ones Classic Favorites Mini Rigatoni Wit...,Fancy Shredded Sharp Cheddar Cheese,Original Recipe Rice Pudding,Mighty 4 Purple Carrot Blackberry Quinoa & Gre...,Pure Irish Butter,Slow Cooker Tavern-Style Pot Roast Sauce,Gluten Free Organic Soyrizo,Botanically Bright SLS-Free Fluoride-Free Pep...,Reserve Cheddar Cheese,Migrane Acetaminophen Aspirin (NSAID) and Caff...
4903,Smart Ones Classic Favorites Mini Rigatoni Wit...,Slow Cooker Tavern-Style Pot Roast Sauce,"Cake, Lemon",Invisible Solid Unscented Deodorant,Sliced Peaches,"Mini I.D.'s French Vanilla Creamer, Singles",Original Recipe Rice Pudding,Yellow Corn Extra Thin Tortillas,Mighty 4 Purple Carrot Blackberry Quinoa & Gre...,Pure Irish Butter
5942,Smart Ones Classic Favorites Mini Rigatoni Wit...,Fancy Shredded Sharp Cheddar Cheese,Original Recipe Rice Pudding,Mighty 4 Purple Carrot Blackberry Quinoa & Gre...,Pure Irish Butter,Slow Cooker Tavern-Style Pot Roast Sauce,Gluten Free Organic Soyrizo,Botanically Bright SLS-Free Fluoride-Free Pep...,Reserve Cheddar Cheese,Migrane Acetaminophen Aspirin (NSAID) and Caff...
8073,Smart Ones Classic Favorites Mini Rigatoni Wit...,Fancy Shredded Sharp Cheddar Cheese,Original Recipe Rice Pudding,Mighty 4 Purple Carrot Blackberry Quinoa & Gre...,Pure Irish Butter,Slow Cooker Tavern-Style Pot Roast Sauce,Gluten Free Organic Soyrizo,Botanically Bright SLS-Free Fluoride-Free Pep...,Reserve Cheddar Cheese,Migrane Acetaminophen Aspirin (NSAID) and Caff...
10025,Smart Ones Classic Favorites Mini Rigatoni Wit...,Wheat English Muffins,Fresh Organic Carrots,Pure Irish Butter,Slow Cooker Tavern-Style Pot Roast Sauce,Gluten Free Organic Soyrizo,Botanically Bright SLS-Free Fluoride-Free Pep...,Reserve Cheddar Cheese,Migrane Acetaminophen Aspirin (NSAID) and Caff...,Fancy Shredded Sharp Cheddar Cheese
...,...,...,...,...,...,...,...,...,...,...
196043,Smart Ones Classic Favorites Mini Rigatoni Wit...,Pure Irish Butter,Jumbo Veggie Protein Smart Dogs Links,"Cake, Lemon",ReNu Sensitive Gentle Formula Multi-Purpose So...,Invisible Solid Unscented Deodorant,"Mini I.D.'s French Vanilla Creamer, Singles",Original Recipe Rice Pudding,Yellow Corn Extra Thin Tortillas,Mighty 4 Purple Carrot Blackberry Quinoa & Gre...
197245,Smart Ones Classic Favorites Mini Rigatoni Wit...,Pure Irish Butter,Blazin' Beef Recipe Dog Food,ReNu Sensitive Gentle Formula Multi-Purpose So...,Invisible Solid Unscented Deodorant,Sliced Peaches,"Mini I.D.'s French Vanilla Creamer, Singles",Original Recipe Rice Pudding,Yellow Corn Extra Thin Tortillas,Mighty 4 Purple Carrot Blackberry Quinoa & Gre...
200396,Smart Ones Classic Favorites Mini Rigatoni Wit...,Gluten Free Organic Soyrizo,ReNu Sensitive Gentle Formula Multi-Purpose So...,Sliced Peaches,"Mini I.D.'s French Vanilla Creamer, Singles",Original Recipe Rice Pudding,Yellow Corn Extra Thin Tortillas,Mighty 4 Purple Carrot Blackberry Quinoa & Gre...,Pure Irish Butter,Slow Cooker Tavern-Style Pot Roast Sauce
202323,Smart Ones Classic Favorites Mini Rigatoni Wit...,Gluten Free Organic Soyrizo,ReNu Sensitive Gentle Formula Multi-Purpose So...,Sliced Peaches,"Mini I.D.'s French Vanilla Creamer, Singles",Original Recipe Rice Pudding,Yellow Corn Extra Thin Tortillas,Mighty 4 Purple Carrot Blackberry Quinoa & Gre...,Pure Irish Butter,Slow Cooker Tavern-Style Pot Roast Sauce
202330,Smart Ones Classic Favorites Mini Rigatoni Wit...,Organic Coconut Covered in Dark Chocolate Cand...,Yellow Corn Extra Thin Tortillas,Pure Irish Butter,Slow Cooker Tavern-Style Pot Roast Sauce,Gluten Free Organic Soyrizo,Botanically Bright SLS-Free Fluoride-Free Pep...,Reserve Cheddar Cheese,Migrane Acetaminophen Aspirin (NSAID) and Caff...,Fancy Shredded Sharp Cheddar Cheese

In [87]:
tableau.to_csv("Tableau.csv",index=True)

In [ ]:
prods_rec.to_csv("Product_recommendations.csv",index=True)